services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: main_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_URL: postgresql+asyncpg://youruser:yourpassword@db:5432/main_db
      SECRET_KEY: my_test_secret_key_12345
    ports:
      - "8000:8000"

volumes:
  pgdata: